### ISSUE TITLE
Adatlapon tetszőleges kép lehesen háttér

### ISSUE THREAD

**Issue by djozike** [djozike/DogsWorld#12]
Adatlapoknál ne csak hátér színt lehesen megadni, hanem lehessen háttérnek képet is megadni (mint a falkáknál)

Probléma: az adatlap bal és jobb alsó sarka lekerekitett, ezt a lekerekitest keppel oldajuk meg igy ha egy tetszoleges hatterkepunk van nem lehet normalisan megcsinalni ezeket a lekerekitett sarkokat

**Comment by Yuyumiko** [comment]
Mi lenne, ha lehetne az adatlapoknak keretet adni? Lenne xy keret, amikből lehetne választani.
