### ISSUE TITLE
egyszerre több kutyának üzenet küldés

### ISSUE THREAD

**Issue by djozike** [djozike/DogsWorld#13]
Többször felmerült az ötlet, hogy több kutyának is lehessen üzenetet küldeni egyszerre.

Ezt hogy tudnánk megvalósítani?
Lehessen csoportokat létrehozni, mint facen és abba lehetne kommunikálni kettőnél több embernek?
Simán lehessen felsorolni 1nél több címzettet vesszővel elválasztva és kiküldeni ugy az üzeeteket mint ahogy a falka körlevél müködik most?

Ötleteket! Vitát!

**Comment by Yuyumiko** [comment]
Szerintem a , elválasztás a legjobb megoldás. Esetleg még az, hogy "szövegdobozok" vannak, ahova be kell írni a kutyák nevét, egy "szövegdobozba" egy kutya nevet lehet írni, és ezekel lehet bővíteni. Ezeket szépen egymás mellé teszi, és automatikusan elválasztja egy vessző. A sor végén pedig lehethe egy "+" amire rákattintva bővíteni lehetne.

**Comment by djozike** [comment]
Készen lett közben
