### ISSUE TITLE
Közös fórumok

### ISSUE THREAD

**Issue by LaureN74** [djozike/DogsWorld#21]
Ha már amúgy is bevezetésre kerül ez a heti "meeting", valami közös fórumot vagy chatet nem lehetne gyártani, ahol folyamatosan tudunk dumálni? Csak a "vezetőség"?

**Comment by djozike** [comment]
légyszi beszédesebb nevet adj az ötleteknek. PL közös fórumok.

**Comment by Yuyumiko** [comment]
Egy közös fórum jó lenne :)

**Comment by djozike** [comment]
megvan az fb csoport
