### ISSUE TITLE
Fajták

### ISSUE THREAD

**Issue by LaureN74** [djozike/DogsWorld#27]
1.Át kéne gondolni,milyen fajták kellenek. Alap fajok hiányoznak,amik közkedveltek, pl. labrador egyáltalán nincs?! Ez nem "túl nagy macera", hiszen ebből csak 3 szín létezik, zsemle, csoki és fekete. Magyar fajtákat is be lehetne venni, mint a mudi és a magyar vizsla,puli, komondor/  továbbá elég kedvelt a csivava, cocker spániel, staffordshire is. 
1. Ha két különböző fajta utódja a kölyök, a fajtája keverékre változna. A fajtatiszta kutyákat lehetne törzskönyveztetni, ezekért többet lehet kérni a piacon, illetve menhelyet létrehozni, ahova a nem kívánt kutyát be lehetne rakni. A humánus megoldás miatt ezek nem törlődnének ha nem kell már a gazdának, de be lehetne fogadni pár ossáért cserébe.

Leginkább csinálnék kategóriákat:
-magyar (szerintem egy gyerekeknek szóló magyar nyelvű honlapon fontos, hogy megismerjék a magyar kutyafajtákat, Lehetne egy kis zászlóval jelölni őket. Akár.)
-ritka (kishu (4 db van belőle, a többi egyedi képpel van!), sarlaoosi (3 db), csehszlovák (8, többi egyedi képpel van))
-népszerű, közkedvelt (több van belőle, és a való életben is kedveltek)
 vagy
-munkakutya, stb.. (pl. malamut, husky, német juhász..)

**Comment by djozike** [comment]
nagyjából kész :)
