### ISSUE TITLE
Javítandó

### ISSUE THREAD

**Issue by LaureN74** [djozike/DogsWorld#28]
1. Amint megtanult mindent a kutya, üres ablak jelenik meg mindkét helyen, ha rákattintok, kidob az oldalról + néha bejelentett leveleknél is
2. "A farkasaimnál van 5 csontos nyakörv Boothnál (amstaff) pedig nem lehet olyat venni. Ez miért van? Mellesleg a farkasoknál rossz helyre teszi a rendszer a nyakörvet."

**Comment by LaureN74** [comment]
3.Rámegyek az egyedi kutyás kiírásra és fehér mindenséget ad ki. Akkor most éppen nem lehet még csak hirdetést sem gyűjteni, hogy később egyedi képet rakhassak be,

**Comment by Yuyumiko** [comment]
A 3.-as megoldva :) A böngészővel volt a gond.
Tudtommal jelenleg csak a Firefoxnál van ez, majd a későbbiekben lehet nem lenne hátrányos a többinél is kipróbálni.

Hiba jelensége: A hirdetéseket nem tölti be(http://kepkezelo.com/images/occphs488lna19076kys.jpg)

**Comment by djozike** [comment]
2.-at még ki kell vizsgálnom, többi javitva

**Comment by Yuyumiko** [comment]
A farkasok miért lettek ilyen nagyok?
Régen kisebb képük volt, nem lehet, hogy ezért teszi rossz helyre a tárgyakat?

**Comment by Wisterya** [comment]
Amikor a falkánk 1. helyezést ér el, akkor 10 csontot kap a vezető. Na most, nekem legutóbb 2x küldte el a 10 csontot.

**Comment by djozike** [comment]
Tudomasom szerint javítva lett minden.
