### ISSUE TITLE
Dán Dog képek

### ISSUE THREAD

**Issue by Wisterya** [djozike/DogsWorld#31]
![dandog1](https://cloud.githubusercontent.com/assets/23195275/19904211/093201fa-a072-11e6-8d98-a43667588abd.png)
![dandog2](https://cloud.githubusercontent.com/assets/23195275/19904216/09769b94-a072-11e6-9c9c-e1db4fa99bd8.png)
![dandog3](https://cloud.githubusercontent.com/assets/23195275/19904215/0939b882-a072-11e6-824e-291b83b65f43.png)
![dandog4](https://cloud.githubusercontent.com/assets/23195275/19904213/0934fcc0-a072-11e6-9878-4033aaeb4f4c.png)
![dandog5](https://cloud.githubusercontent.com/assets/23195275/19904212/0932c9d2-a072-11e6-8be6-2cd8fb6a2051.png)
![dandog6](https://cloud.githubusercontent.com/assets/23195275/19904214/09393b00-a072-11e6-9765-f017e7f78b7e.png)
![dandog7](https://cloud.githubusercontent.com/assets/23195275/19904217/097c8e28-a072-11e6-839f-0021b3f6b718.png)
![dandog8](https://cloud.githubusercontent.com/assets/23195275/19904218/097dd224-a072-11e6-877e-1267a6f83820.png)
![dandog9](https://cloud.githubusercontent.com/assets/23195275/19904219/098b429c-a072-11e6-910b-376bffa1abd6.png)
![dandog10](https://cloud.githubusercontent.com/assets/23195275/19904221/098cf434-a072-11e6-826c-c0b9eb8cbafb.png)
![dandog11](https://cloud.githubusercontent.com/assets/23195275/19904220/098bd630-a072-11e6-86fe-e2e8c1c166e2.png)
![dandog12](https://cloud.githubusercontent.com/assets/23195275/19904222/09c3b9e2-a072-11e6-91d1-27d6894d6697.png)
![dandog13](https://cloud.githubusercontent.com/assets/23195275/19904223/09d5c4ca-a072-11e6-86b9-dcb03b414efd.png)
![dandog14](https://cloud.githubusercontent.com/assets/23195275/19904224/09dca772-a072-11e6-9c59-2386c24d860b.png)
![dandog15](https://cloud.githubusercontent.com/assets/23195275/19904225/09f266a2-a072-11e6-9e19-3967f54c1683.png)
![dandog16](https://cloud.githubusercontent.com/assets/23195275/19904226/09f3757e-a072-11e6-95fb-f9f09b96c8c9.png)
![dandog17](https://cloud.githubusercontent.com/assets/23195275/19904227/09f75716-a072-11e6-8d35-c27bc68c10ee.png)
![dandog18](https://cloud.githubusercontent.com/assets/23195275/19904228/09ff62d0-a072-11e6-9361-04466037cfce.png)
![dandog19](https://cloud.githubusercontent.com/assets/23195275/19904229/0a028640-a072-11e6-8c47-f200ab0cd2ab.png)
![dandog20](https://cloud.githubusercontent.com/assets/23195275/19904230/0a07ddac-a072-11e6-9100-821dacb72b78.png)
![dandog21](https://cloud.githubusercontent.com/assets/23195275/19904231/0a20d276-a072-11e6-9bd0-85d63d88b6e2.png)
![dandog22](https://cloud.githubusercontent.com/assets/23195275/19904232/0a27e494-a072-11e6-96c8-2147f08ff412.png)
![dandog23](https://cloud.githubusercontent.com/assets/23195275/19904233/0a365bdc-a072-11e6-8f87-045e1d859ddf.png)
![dandog24](https://cloud.githubusercontent.com/assets/23195275/19904234/0a524932-a072-11e6-9888-c8d611f239bf.png)

**Comment by Wisterya** [comment]
Itt vannak a Dán (Német) Dogok. Ha valamelyiknél valamilyen gáz van, szóljatok.
/Seth

**Comment by Yuyumiko** [comment]
Biztos jó ötlet ezeket a képeket felhasználni? Attól tartok, hogy hiszti lesz belőle, hogy a dw csak kopizza a kn-t.
Sajnos ebben már így is benne vagyunk kicsit, mivel a dw később lett mint a kn, és nem tudják a két oldal eredetének a történetét.
A fórumoknál is valaki említette azt, hogy nálunk is legyen speciális kutyák(azok a színesek), és sokan lehurrogták, hogy "ez copy" meg "A dw ne utánozza a kn-t, legyen önmaga".
Szerintem is az lenne a helyes út, ha a két oldal minél jobban külön tudna válni. Mivel a kn adminjai nem tudnak az oldalukon változtatni, ezért a dw-t kell fejleszteni. Egyre jobban önálló lett számomra a dw, és attól tartok, hogy ha most a semmiből bevezetünk egy új kutyát, a kn képeivel, akkor az oldal támadhatóvá válik.
Továbbá én inkább azt támogatnám, hogy első sorban a magyar fajtákat vezessük be :)
Ez csak az én véleményem, amit úgy gondoltam, hogy megosztok veletek. És természetesen támogatom az új fajták bevezetését, de akkor saját képekkel :)
