### ISSUE TITLE
Karácsonyi játék

### ISSUE THREAD

**Issue by Yuyumiko** [djozike/DogsWorld#33]
Ide teszem fel az elkészült karácsonyi dolgokat :)

**Comment by Yuyumiko** [comment]
Díszek:
![disz1](https://cloud.githubusercontent.com/assets/12499500/20240996/0644072c-a928-11e6-84f8-39bd89213c84.png)
![disz2](https://cloud.githubusercontent.com/assets/12499500/20240998/0b3c2d22-a928-11e6-96c4-c036a5b7fe66.png)
![disz3](https://cloud.githubusercontent.com/assets/12499500/20240999/0fd14b1a-a928-11e6-8da7-7260f55ee59c.png)
![disz4](https://cloud.githubusercontent.com/assets/12499500/20241000/132645b8-a928-11e6-86f3-f303c55325fb.png)
![disz5](https://cloud.githubusercontent.com/assets/12499500/20241001/16c7de0c-a928-11e6-939e-1f87231431d5.png)
![disz6](https://cloud.githubusercontent.com/assets/12499500/20241002/19bde160-a928-11e6-90d7-3a927ef71edf.png)

**Comment by Wisterya** [comment]
Nagyon jól néznek ki! :D

**Comment by Yuyumiko** [comment]
Köszi :)

Mikulássapkák egy része:
Akita Inu:
![mikulassapkaakita](https://cloud.githubusercontent.com/assets/12499500/20447806/219d34f4-ade1-11e6-9d6f-a63afc49368d.png)

Amerikai Bulldog:
![mikulassapkaamerikaibuldog](https://cloud.githubusercontent.com/assets/12499500/20447824/2e55e25e-ade1-11e6-9292-d9b72ebad88b.png)

Amerikai Staffordshire Terrier:
![mikulassapkaamstate](https://cloud.githubusercontent.com/assets/12499500/20447844/4c02c07e-ade1-11e6-9055-880e3f74640f.png)

Basenji:
![mikulassapkaamstate](https://cloud.githubusercontent.com/assets/12499500/20447829/37566ab8-ade1-11e6-83a3-06dbab695218.png)

Belga Juhász:
![mikulassapkabelgajuhaszkutya](https://cloud.githubusercontent.com/assets/12499500/20447854/5436b5d4-ade1-11e6-9412-06fec4e0b5b2.png)

**Comment by Yuyumiko** [comment]
Border Collie:
![mikulassapkabordercollie](https://cloud.githubusercontent.com/assets/12499500/20449855/3f541548-adec-11e6-953d-fc34a4bd13bc.png)

Boxer:
![mikulassapkaboxer](https://cloud.githubusercontent.com/assets/12499500/20449856/44869126-adec-11e6-905f-591e76872054.png)

Csehszlovák Farkas:
![mikulassapkacsehszlovakfarkas](https://cloud.githubusercontent.com/assets/12499500/20449861/4fb4124e-adec-11e6-850d-bbcb8c34c9a7.png)

Dalmata:
![mikulassapkadalmata](https://cloud.githubusercontent.com/assets/12499500/20449864/54d94a32-adec-11e6-9917-fb65c0c2e0ce.png)

Dobermann:
![mikulassapkadobermann](https://cloud.githubusercontent.com/assets/12499500/20449867/5beaccf6-adec-11e6-8340-3e40e644512b.png)

**Comment by Yuyumiko** [comment]
Farkas:
![mikulassapkafarkas](https://cloud.githubusercontent.com/assets/12499500/20454407/95d560d0-ae40-11e6-82ef-bb2369a2ba97.png)

Welsh Corgie:
![mikulassapkafawn](https://cloud.githubusercontent.com/assets/12499500/20454410/a293e9ea-ae40-11e6-8321-b56583badbbb.png)

Finnlap Kutya:
![mikulassapkafinnlapkutya](https://cloud.githubusercontent.com/assets/12499500/20454413/ad9d397c-ae40-11e6-9473-46231473b6fd.png)

Golden Retriever:
![mikulassapkagoldenretriever](https://cloud.githubusercontent.com/assets/12499500/20454417/bb4ba798-ae40-11e6-8efb-df9ffd506c85.png)

Husky:
![mikulassapkahusky](https://cloud.githubusercontent.com/assets/12499500/20454423/ce494652-ae40-11e6-87ba-0fef3b0b38f7.png)

Kánaán Kutya:
![mikulassapkakanaankutya](https://cloud.githubusercontent.com/assets/12499500/20454422/c22203be-ae40-11e6-93fb-1de6bc2111ec.png)

Kishu Inu:
![mikulassapkakishuinu](https://cloud.githubusercontent.com/assets/12499500/20454432/f4a47d94-ae40-11e6-883f-346a6a6fe7e8.png)

Kuvasz:
![mikulassapkakuvasz](https://cloud.githubusercontent.com/assets/12499500/20454428/e11d8eaa-ae40-11e6-9bf7-f6113702759f.png)

Malamut:
![mikulassapkamalamut](https://cloud.githubusercontent.com/assets/12499500/20454430/e852198e-ae40-11e6-9f86-b7b4a343ac8a.png)

Mopsz:
![mikulassapkamops](https://cloud.githubusercontent.com/assets/12499500/20454435/fde0a6c6-ae40-11e6-9b5d-0befc97f20d2.png)

**Comment by Yuyumiko** [comment]
Német Juhász:
![mikulassapkanemetjuhaszkutya](https://cloud.githubusercontent.com/assets/12499500/20454604/0267a078-ae46-11e6-9ff4-d558800a66c1.png)

Pitbull:
![mikulassapkapitbull](https://cloud.githubusercontent.com/assets/12499500/20454607/0b48f2a0-ae46-11e6-938f-e2df969efcfa.png)

Rotweiller:
![mikulassapkarotweiller](https://cloud.githubusercontent.com/assets/12499500/20454608/14b58e2a-ae46-11e6-84f6-656c3c4aa293.png)

Saarloosi:
![mikulassapkasaarloosi](https://cloud.githubusercontent.com/assets/12499500/20454609/1c8aa784-ae46-11e6-9265-7eda96018d19.png)

Shar-pei:
![mikulassapkasharpei](https://cloud.githubusercontent.com/assets/12499500/20454611/25dd4148-ae46-11e6-9f11-a65b23ce2ba2.png)

Si-cu:
![mikulassapkasicu](https://cloud.githubusercontent.com/assets/12499500/20454613/2ea27686-ae46-11e6-9ec6-33fc07391fdb.png)

Tacskó:
![mikulassapkatacsko](https://cloud.githubusercontent.com/assets/12499500/20454614/34084c40-ae46-11e6-8c09-bd949e8b14c0.png)

Uszkár:
![mikulassapkauszkar](https://cloud.githubusercontent.com/assets/12499500/20454615/3a7f820a-ae46-11e6-93e4-a4f01c91c926.png)

**Comment by Yuyumiko** [comment]
Beagle:
![mikulassapkabeagle](https://cloud.githubusercontent.com/assets/12499500/20529921/29bee31e-b0d2-11e6-98fc-1f83d206c341.png)

Izlandi Juhász:
![mikulassapkaicelandic](https://cloud.githubusercontent.com/assets/12499500/20529941/34eaf26e-b0d2-11e6-808e-96218ffb355f.png)

Papillon:
![mikulassapkapapillon](https://cloud.githubusercontent.com/assets/12499500/20529958/3e0ae75a-b0d2-11e6-8b66-f224779a53b4.png)

Thai ridgeback:
![mikulassapkathai](https://cloud.githubusercontent.com/assets/12499500/20529972/47424cfa-b0d2-11e6-8315-b8d9e5a7b612.png)

westie:
![mikulassapkawestie](https://cloud.githubusercontent.com/assets/12499500/20529988/4f26d490-b0d2-11e6-97ea-5a820b720f94.png)

Whippet:
![mikulassapkawhippet](https://cloud.githubusercontent.com/assets/12499500/20529996/55a2a100-b0d2-11e6-9245-5a6ce05f25d2.png)

Yorkie:
![mikulassapkayorkie](https://cloud.githubusercontent.com/assets/12499500/20530003/5b210630-b0d2-11e6-81fa-737f83fb88eb.png)

Ezzel a sapkák készen vannak, azokra a fajtákra nem lettek méretezve, amelyekből nincs egy se.

A sapka:
![1](https://cloud.githubusercontent.com/assets/12499500/20530046/77807afe-b0d2-11e6-925a-9124e3c441dd.png)
