### ISSUE TITLE
nem vásárolható tárgyak

### ISSUE THREAD

**Issue by djozike** [djozike/DogsWorld#40]
legyenek olyan tárgyak is amiket nem lehet csontért megvenni.

**Comment by Yuyumiko** [comment]
Ezek a tárgyak lehetnének az esemény tárgyak, amiket csak ünnepekkor lehetne elérni(pl.: A mikál sapit csak karácsonykor lehetne megszerezni karácsonyfa díszek beváltásával)

**Comment by djozike** [comment]
pontosan erre gondoltam :)

-Karacsonyi Nyakőrv
-Mikulás sapka
-esetleg húsvéti tojások
