### ISSUE TITLE
Tárgy elcsuszások

### ISSUE THREAD

**Issue by djozike** [djozike/DogsWorld#42]
Jópár kutyán elvannak csúszva a tárgyak. Ezeket javítani kellene. Elméletileg Seth dolgozik már rajta de azért csináltam ide is egy ilyent. Hogy látszodjon, hogy ez is aktuális feladat.

**Comment by Wisterya** [comment]
Csinálom

**Comment by djozike** [comment]
elcsúszottak:
-basset hound (2 nyakörv)
-shar-pei (2 bőr nyakörv)
-basenji (mikulás sapka)
-pitbull (2 bőr nyakörv)
-mops

**Comment by djozike** [comment]
Mi a helyzet ezzel? Mikor lesz meg?

**Comment by Zsofi99** [comment]
Mopsz nyakörvek

![mopsfeketebornyakorv](https://user-images.githubusercontent.com/25252055/26896123-115d788e-4bc4-11e7-8bb1-cf060e9d556d.png)
![mopsbarnabornyakorv](https://user-images.githubusercontent.com/25252055/26896133-18c90b7e-4bc4-11e7-91fc-04afebc28f76.png)

**Comment by Zsofi99** [comment]
Első próbál pitbull mikulás sali. Ha így sem jó, akkor próbálkozopróbálkozom tovább vele.
![pitbullmikulas](https://user-images.githubusercontent.com/25252055/26898080-006404ba-4bcb-11e7-996a-a4a1a5ed61c3.png)

**Comment by Zsofi99** [comment]
Pitbull mikulás 2. próba, bal alsó sarok igazítással
![pitbullmikulas](https://user-images.githubusercontent.com/25252055/27010468-31d19f12-4ea5-11e7-8c04-4ad365f6ab03.png)

**Comment by Zsofi99** [comment]
Mopsz mikulás 1. próba, bal alsó sarokkal
![mopsmikulas](https://user-images.githubusercontent.com/25252055/27010490-2b525be4-4ea6-11e7-99ca-2ef9eb8593b4.png)

**Comment by Zsofi99** [comment]
Bernáthegyi fekete bőrnyakörv
![bernathegyifeketebornyakorv](https://user-images.githubusercontent.com/25252055/27010697-9ec93594-4eaa-11e7-89f3-d7c2696f9601.png)

**Comment by Zsofi99** [comment]
Ééés a bernathegyi barna bőrnyakörv :)
![bernathegyibarnabornyakorv](https://user-images.githubusercontent.com/25252055/27011378-b66607e4-4eba-11e7-80fc-8cdd9b286b8c.png)
