### ISSUE TITLE
tárgy készítés

### ISSUE THREAD

**Issue by djozike** [djozike/DogsWorld#48]
új lecke, amivel tárgyakat lehetne kezdetbe csak átszínezni, de később akár új tárgyakat is gyártani. 

PL ha van mikulás sapkája és sok zöld vagy kék festéke akkor a festékek felhasználásával atszinezheti zöld/kékre a sapkáját.

**Comment by Yuyumiko** [comment]
Vagy ásásnál lehetne minden féle eszközt találni, pl.: cérnát, amikből ha eleget talál, akkor tárgyakat rakhat össze. Így nem csak bolti meg eseményi tárgyak lehetnének

**Comment by djozike** [comment]
igen hosszutavon abszolut igy kepzelem el, h majd kulonbozo dolgokat csinalhatnak a kutyak amiert kaphatnak kajat, targyakat, vagy alapanyagokat amiket felhasznalhatnak targyak keszitesere
