### ISSUE TITLE
Lottónyeremény

### ISSUE THREAD

**Issue by Zsofi99** [djozike/DogsWorld#52]
Nagyon kevesen játszanak a lottón a kevés nyeremény miatt. Ha az egyedi kutyára, névváltoztatásra, tárgyakra költött csont, illetve a piacról levont százalékot a rendszer jóváírná plusz nyereményként a lottón, akkor a növekvő nyeremény, növelné az érdeklődést is, nem válna feleslegessé a játék.

**Comment by djozike** [comment]
Azt tudom elképzelni, hogy megemeljük az egyedi kutya árát 2 csonttal és az a 2 csont meg a lottoba

**Comment by Zsofi99** [comment]
Így is javítana az érdeklődésen :)
