### ISSUE TITLE
Kölyök kutyáknál nem másolodik az e-mail cim

### ISSUE THREAD

**Issue by djozike** [djozike/DogsWorld#54]

**Comment by Zsofi99** [comment]
Ez a gond már régebben is előjött. Nem tudom emlékszel-e amikor facen küldtem a képet Woods oldaláról a kölyök elnevezése után. Annak a kölyöknek sem másolódott már az email,  csak akkor még azt hittük hogy lokális a probléma. Abban az időben lett változtatva a gének öröklődése random rendszerről a jelenlegire. Nem lehet hogy ott csúszott el valami?

**Comment by djozike** [comment]
Eletileg a piac megvetelnel volt elrontva es innentol jo lesz
