### ISSUE TITLE
Régi tojások fajtánként 

### ISSUE THREAD

**Issue by Zsofi99** [djozike/DogsWorld#57]
Ide fogom feltölteni az elkészült tojásokat, fajtánként :)

**Comment by Zsofi99** [comment]
## Basset hound
![bassethoundfehertojas](https://cloud.githubusercontent.com/assets/25252055/22622077/4275ac36-eb32-11e6-99b1-9ae75bcefdb3.png)
![bassethoundpirostojas](https://cloud.githubusercontent.com/assets/25252055/22622080/427912d6-eb32-11e6-8751-69bfee12f4a6.png)
![bassethoundsargatojas](https://cloud.githubusercontent.com/assets/25252055/22622076/42730c56-eb32-11e6-83ec-0585ca93858d.png)
![bassethoundzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22622078/427878c6-eb32-11e6-879e-bb1cab2b468b.png)
## Beagle (piros és zöld már volt elvileg)
![beaglefehertojas](https://cloud.githubusercontent.com/assets/25252055/22622081/427b82aa-eb32-11e6-8091-ea3dd7131743.png)
![beaglesargatojas](https://cloud.githubusercontent.com/assets/25252055/22622082/4291085a-eb32-11e6-9491-d80c758d7d2f.png)
## Német dog
![dandogfehertojas](https://cloud.githubusercontent.com/assets/25252055/22622084/429953f2-eb32-11e6-83c1-498b9a09d541.png)
![dandogpirostojas](https://cloud.githubusercontent.com/assets/25252055/22622085/429ccda2-eb32-11e6-8c45-1a130acea699.png)
![dandogsargatojas](https://cloud.githubusercontent.com/assets/25252055/22622086/429eb496-eb32-11e6-99d0-f8e4a5dd349a.png)
![dandogzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22622087/42a20e48-eb32-11e6-9ec0-f8305aebe4b0.png)
##Farkas
![farkasfehertojas](https://cloud.githubusercontent.com/assets/25252055/22622088/42b233fe-eb32-11e6-80fd-7e8b48beaf99.png)
![farkaspirostojas](https://cloud.githubusercontent.com/assets/25252055/22622089/42bb7bc6-eb32-11e6-8aab-b7dcff7ae8d2.png)
![farkassargatojas](https://cloud.githubusercontent.com/assets/25252055/22622090/42bd061c-eb32-11e6-9f35-b0d6d6587e9a.png)
![farkaszoldtojas](https://cloud.githubusercontent.com/assets/25252055/22622091/42bf94d6-eb32-11e6-9274-d6502eb0d12b.png)
## Kuvasz
![kuvaszfehertojas](https://cloud.githubusercontent.com/assets/25252055/22622092/42c22070-eb32-11e6-8a28-5b3e945406ae.png)
![kuvaszpirostojas](https://cloud.githubusercontent.com/assets/25252055/22622093/42c796ae-eb32-11e6-90df-57b5ce0af046.png)
![kuvaszsargatojas](https://cloud.githubusercontent.com/assets/25252055/22622094/42d2de24-eb32-11e6-91bb-31a3267d9a24.png)
![kuvaszzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22622095/42db48ac-eb32-11e6-99b4-f9edb400174e.png)
## Pitbull
![pitbullfehertojas](https://cloud.githubusercontent.com/assets/25252055/22622097/42df7166-eb32-11e6-8bae-29481c62acfb.png)
![pitbullpirostojas](https://cloud.githubusercontent.com/assets/25252055/22622096/42df1626-eb32-11e6-8ca2-5a979f33c5e7.png)
![pitbullsargatojas](https://cloud.githubusercontent.com/assets/25252055/22622098/42e33422-eb32-11e6-9fb5-35787d1c4c6e.png)
![pitbullzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22622099/42e57660-eb32-11e6-9065-85fd81a0d0c2.png)
## Shar-pei
![sharpeifehertojas](https://cloud.githubusercontent.com/assets/25252055/22622100/42effe78-eb32-11e6-9cdc-4096694ac833.png)
![sharpeipirostojas](https://cloud.githubusercontent.com/assets/25252055/22622101/42fd1b76-eb32-11e6-822c-8a6a9fd7d83f.png)
![sharpeisargatojas](https://cloud.githubusercontent.com/assets/25252055/22622103/430393c0-eb32-11e6-9ff5-b87c51d37575.png)
![sharpeizoldtojas](https://cloud.githubusercontent.com/assets/25252055/22622102/4302fe92-eb32-11e6-9a10-4a9070a97c73.png)
## Yorki
![yorkifehertojas](https://cloud.githubusercontent.com/assets/25252055/22622104/43053982-eb32-11e6-8294-88d60fc8fd31.png)
![yorkipirostojas](https://cloud.githubusercontent.com/assets/25252055/22622106/430eabd4-eb32-11e6-9c3e-7e97974e8992.png)
![yorkisargatojas](https://cloud.githubusercontent.com/assets/25252055/22622105/430e7fba-eb32-11e6-8487-81219605abc6.png)
![yorkizoldtojas](https://cloud.githubusercontent.com/assets/25252055/22622107/431d7cae-eb32-11e6-9ca6-4512339118d8.png)

**Comment by Zsofi99** [comment]
##Bernáthegyi 
![bernathegyifehertojas](https://cloud.githubusercontent.com/assets/25252055/22980245/4de2ee20-f399-11e6-9dd7-33b85c325488.png)
![bernathegyipirostojas](https://cloud.githubusercontent.com/assets/25252055/22980246/4de4b0de-f399-11e6-9605-b385180424ef.png)
![bernathegyisargatojas](https://cloud.githubusercontent.com/assets/25252055/22980244/4de2cc92-f399-11e6-84ee-a7184fd9872a.png)
![bernathegyizoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980247/4de5c154-f399-11e6-8584-ebae0d995b37.png)
##Bullterrier
![bullterrierfehertojas](https://cloud.githubusercontent.com/assets/25252055/22980248/4df0cb62-f399-11e6-8392-b6e78a136e4f.png)
![bullterrierpirostojas](https://cloud.githubusercontent.com/assets/25252055/22980250/4e08156a-f399-11e6-8cf4-16ba132077dc.png)
![bullterriersargatojas](https://cloud.githubusercontent.com/assets/25252055/22980255/4e1980b6-f399-11e6-93a0-81c1d2022547.png)
![bullterrierzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980252/4e0bd2d6-f399-11e6-9665-67e5f4cf19a1.png)
##Dobermann
![dobermannfehertojas](https://cloud.githubusercontent.com/assets/25252055/22980251/4e09e0a2-f399-11e6-991c-ff30d562f6d6.png)
![dobermannpirostojas](https://cloud.githubusercontent.com/assets/25252055/22980254/4e16eb94-f399-11e6-81b3-58e732708040.png)
![dobermannsargatojas](https://cloud.githubusercontent.com/assets/25252055/22980253/4e169928-f399-11e6-9e59-2d978e23dbcb.png)
![dobermannzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980256/4e2d8e80-f399-11e6-9c00-06ec1a5bd4b9.png)
##Golden retriever
![goldenretriverfehertojas](https://cloud.githubusercontent.com/assets/25252055/22980261/4e467490-f399-11e6-9dca-308a60167300.png)
![goldenretriverpirostojas](https://cloud.githubusercontent.com/assets/25252055/22980258/4e321c48-f399-11e6-99d0-d24407365ed9.png)
![goldenretriversargatojas](https://cloud.githubusercontent.com/assets/25252055/22980260/4e40f704-f399-11e6-9172-b1c34f6f7ef2.png)
![goldenretriverzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980263/4e592ee6-f399-11e6-8ed6-c9c0fbc5aa03.png)
##Kaukázusi
![kaukazusifehertojas](https://cloud.githubusercontent.com/assets/25252055/22980259/4e3fbe0c-f399-11e6-85a4-76865292c5ba.png)
![kaukazusipirostojas](https://cloud.githubusercontent.com/assets/25252055/22980262/4e55f794-f399-11e6-82ad-e0f3502f0871.png)
![kaukazusisargatojas](https://cloud.githubusercontent.com/assets/25252055/22980264/4e647c4c-f399-11e6-8946-9e0c0de7ae8c.png)
![kaukazusizoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980266/4e69c0a8-f399-11e6-9d31-b48a66ef0e39.png)
##Kínai
![kinaimesztelenkutyafehertojas](https://cloud.githubusercontent.com/assets/25252055/22980265/4e699a92-f399-11e6-9e4f-ad16c75527a0.png)
![kinaimesztelenkutyapirostojas](https://cloud.githubusercontent.com/assets/25252055/22980267/4e7211ea-f399-11e6-844b-bc5e85fa07a8.png)
![kinaimesztelenkutyasargatojas](https://cloud.githubusercontent.com/assets/25252055/22980268/4e97f9f0-f399-11e6-8b1d-419ce7eaae0d.png)
![kinaimesztelenkutyazoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980269/4e9ba3f2-f399-11e6-8bd8-3b98dfacceef.png)
##King Charles
![kingcharlesfehertojas](https://cloud.githubusercontent.com/assets/25252055/22980273/4eb552f2-f399-11e6-84f9-30a4f41a98e7.png)
![kingcharlespirostojas](https://cloud.githubusercontent.com/assets/25252055/22980271/4ea36d30-f399-11e6-8122-7c3c40094ce4.png)
![kingcharlessargatojas](https://cloud.githubusercontent.com/assets/25252055/22980272/4eb00644-f399-11e6-8b9f-79233945a23b.png)
![kingcharleszoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980270/4ea26a2a-f399-11e6-8c0c-d9058628baf5.png)
##Maltese
![maltesefehertojas](https://cloud.githubusercontent.com/assets/25252055/22980275/4ec155b6-f399-11e6-9753-504b1d2f3cd1.png)
![maltesepirostojas](https://cloud.githubusercontent.com/assets/25252055/22980283/4f01e298-f399-11e6-9642-8b29285a0a68.png)
![maltesesargatojas](https://cloud.githubusercontent.com/assets/25252055/22980282/4efa6a40-f399-11e6-8d4f-12fda5395f69.png)
![maltesezoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980278/4ee6b0c2-f399-11e6-8975-010c8886c0f4.png)
##Mopsz
![mopsfehertojas](https://cloud.githubusercontent.com/assets/25252055/22980277/4ed4790c-f399-11e6-8bc9-02583aaaa106.png)
![mopspirostojas](https://cloud.githubusercontent.com/assets/25252055/22980276/4ed2a672-f399-11e6-8a47-c41223e76f3f.png)
![mopssargatojas](https://cloud.githubusercontent.com/assets/25252055/22980279/4ee5aa7e-f399-11e6-94d9-4485323047a6.png)
![mopszoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980280/4ef312e0-f399-11e6-9109-a60291fce539.png)
##Saarloosi
![saarloosifehertojas](https://cloud.githubusercontent.com/assets/25252055/22980281/4efa5528-f399-11e6-89d7-58dcd4f6eb41.png)
![saarloosipirostojas](https://cloud.githubusercontent.com/assets/25252055/22980286/4f13ec54-f399-11e6-8821-35c00a2c8112.png)
![saarloosisargatojas](https://cloud.githubusercontent.com/assets/25252055/22980285/4f13e2c2-f399-11e6-9ac4-bd5c89e67856.png)
![saarloosizoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980289/4f28fedc-f399-11e6-87e2-c83c4c032c27.png)
##Si-cu
![si-cufehertojas](https://cloud.githubusercontent.com/assets/25252055/22980288/4f279150-f399-11e6-8416-ad390e3bd53b.png)
![si-cupirostojas](https://cloud.githubusercontent.com/assets/25252055/22980290/4f2d5342-f399-11e6-95d9-7d72e3275d55.png)
![si-cusargatojas](https://cloud.githubusercontent.com/assets/25252055/22980287/4f27366a-f399-11e6-8595-b175987f5c0f.png)
![si-cuzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980291/4f3ecda2-f399-11e6-825e-8d204194ea21.png)
##Skót juhász
![skotjuhaszfehertojas](https://cloud.githubusercontent.com/assets/25252055/22980293/4f4f686a-f399-11e6-92d9-e9074a361494.png)
![skotjuhaszpirostojas](https://cloud.githubusercontent.com/assets/25252055/22980294/4f543f48-f399-11e6-8975-233a63838cce.png)
![skotjuhaszsargatojas](https://cloud.githubusercontent.com/assets/25252055/22980297/4f6c4b9c-f399-11e6-94e7-a2fb6af5486e.png)
![skotjuhaszzoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980292/4f4de620-f399-11e6-968f-04c2a82e2187.png)
##Tacskó
![tacskofehertojas](https://cloud.githubusercontent.com/assets/25252055/22980295/4f57237a-f399-11e6-9b0f-0f5bb18d070b.png)
![tacskopirostojas](https://cloud.githubusercontent.com/assets/25252055/22980296/4f61814e-f399-11e6-8112-6578796e598b.png)
![tacskosargatojas](https://cloud.githubusercontent.com/assets/25252055/22980298/4f7aada4-f399-11e6-8563-fa3f7de29a4d.png)
![tacskozoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980303/4f960446-f399-11e6-8ba4-975fe0e2ee3c.png)
##Thai
![thaifehertojas](https://cloud.githubusercontent.com/assets/25252055/22980301/4f86e920-f399-11e6-86a3-b2ae3c699a2d.png)
![thaipirostojas](https://cloud.githubusercontent.com/assets/25252055/22980299/4f80dc10-f399-11e6-9e82-0646511e5bf2.png)
![thaisargatojas](https://cloud.githubusercontent.com/assets/25252055/22980300/4f8204d2-f399-11e6-9048-c52c38d40e9b.png)
![thaizoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980308/4fcc334a-f399-11e6-926a-5ac4b781babb.png)
##Westie
![westiefehertojas](https://cloud.githubusercontent.com/assets/25252055/22980305/4fa130e6-f399-11e6-99b2-e9febcfffc06.png)
![westiepirostojas](https://cloud.githubusercontent.com/assets/25252055/22980309/4fcfb290-f399-11e6-8c09-113c9048b044.png)
![westiesargatojas](https://cloud.githubusercontent.com/assets/25252055/22980306/4fc33c4a-f399-11e6-8f78-6db8316cb443.png)
![westiezoldtojas](https://cloud.githubusercontent.com/assets/25252055/22980307/4fc7ad70-f399-11e6-86e3-356923282ec8.png)

**Comment by djozike** [comment]
whippet hiányzik
