### ISSUE TITLE
Biztonság fejlesztése

### ISSUE THREAD

**Issue by Yuyumiko** [djozike/DogsWorld#58]
Jó lenne, ha a kutyákra E-mail cím alapján is rá tudnánk keresni :)
Továbbá az Admin panelen pár egyéb dolog is látható lehetne, nem csak a kutyák előző nevei, hanem mondjuk az előző bejelentkezési IP, ha piacon eladták, akkor ki adta el kinek, régebbi E-mail-ek.
Így könyebben nyomon lehetne követni, hogy kinek ki a kutyája :) Továbbá a lopások is könnyebben visszakereshetőek lehetnének :)

**Comment by Yuyumiko** [comment]
Lehessen a blogolástól is eltiltani

**Comment by djozike** [comment]
meg ha törölt egy blogot az látszodjon csak nekunk egy pár napig még utánna

**Comment by Yuyumiko** [comment]
meg ha törlünk egy blogot, akkor lehessen mellette indoklást is küldeni a tulajnak :)
