### ISSUE TITLE
tárgyak modul befejezése

### ISSUE THREAD

**Issue by djozike** [djozike/DogsWorld#6]
a tárgyak modul befejezése, jópár dolog hiányzik még
a tárgyak levétele a kutyáról
a levétel utánni újbóli felvétel vagy nincs implementálva, de legalább tesztelve nincs
nagyon kevés tárgy van és ezen változtatni se tudok mert nem tudok rajzolni

**Comment by Yuyumiko** [comment]
Akkor folytatom a nyakörvek és egyebek rajzolását :)

**Comment by djozike** [comment]
jajj, egyelőre messze vagyok attol, hogy ez sorra kerüljön, szóval szerintem ne törd magad, viszont amik már elkészültek régebben azokat megoszthatnád velünk.

**Comment by Yuyumiko** [comment]
![bor_nyakorv_1_nemet_juhasz](https://cloud.githubusercontent.com/assets/12499500/7730855/f962b870-ff1c-11e4-9514-67dfca1e20e8.png)
![bor_nyakorv_2_nemet_juhasz](https://cloud.githubusercontent.com/assets/12499500/7730857/fdcc533a-ff1c-11e4-9b71-3beb32533a70.png)

Német juhászra kész nyakörvek(Bőr nyakörv 1;2)

**Comment by djozike** [comment]
A programozás része kész, még az árakat kéne kitalálni, meg több képet csinálni, ezek már nem az én dolgaim ugyhogy átrakom rád a felelőst.

**Comment by Yuyumiko** [comment]
Itt van pár kész:
Basset Hound
![bornyakorvbassethound1](https://cloud.githubusercontent.com/assets/12499500/7812806/01860744-03b6-11e5-8b78-2241630bbec3.png)
![bornyakorvbassethound2](https://cloud.githubusercontent.com/assets/12499500/7812815/088cbbbe-03b6-11e5-97ca-a2c4ba18c014.png)
Border Collie:
![bornyakorvbordercollie1](https://cloud.githubusercontent.com/assets/12499500/7812819/105d52ae-03b6-11e5-96cc-8bf98b05f1dd.png)
![bornyakorvbordercollie2](https://cloud.githubusercontent.com/assets/12499500/7812821/13d28224-03b6-11e5-9da2-81c651b85a67.png)
Bullterrier:
![bornyakorvbullterrier1](https://cloud.githubusercontent.com/assets/12499500/7812830/1f7622f2-03b6-11e5-8e30-34f3d6a4773c.png)

**Comment by Yuyumiko** [comment]
Bulterrier:
![bornyakorvbullterrier2](https://cloud.githubusercontent.com/assets/12499500/7812836/2be78a4e-03b6-11e5-81e1-2994244ef468.png)
Dalmata:
![bornyakorvdalmata1](https://cloud.githubusercontent.com/assets/12499500/7812838/35dc5192-03b6-11e5-80c4-debb74f0b0c5.png)
![bornyakorvdalmata2](https://cloud.githubusercontent.com/assets/12499500/7812842/38334540-03b6-11e5-93bf-27eb67e1ca2f.png)
Farkas:
![bornyakorvfarkas1](https://cloud.githubusercontent.com/assets/12499500/7812857/44dd1532-03b6-11e5-8eff-b0b5b799d45a.png)
![bornyakorvfarkas2](https://cloud.githubusercontent.com/assets/12499500/7812862/4a856124-03b6-11e5-8303-dbbb39b8074f.png)
Finnlappkutya:
![bornyakorvfinnlappkutya1](https://cloud.githubusercontent.com/assets/12499500/7812867/5480d03c-03b6-11e5-96a4-c74bb4976082.png)
![bornyakorvfinnlappkutya2](https://cloud.githubusercontent.com/assets/12499500/7812872/5955cf36-03b6-11e5-8bd1-7011d5488161.png)
Kánaán Kutya:
![bornyakorvkanaankutya1](https://cloud.githubusercontent.com/assets/12499500/7812879/69a77f60-03b6-11e5-88a4-d3c317d93077.png)
![bornyakorvkanaankutya2](https://cloud.githubusercontent.com/assets/12499500/7812881/6f0d761c-03b6-11e5-92d3-06fc7e71a4bc.png)
Kuvasz:
![bornyakorvkuvasz1](https://cloud.githubusercontent.com/assets/12499500/7812888/7ace4f4e-03b6-11e5-8ebe-fb6ca4e7fe7f.png)
![bornyakorvkuvasz2](https://cloud.githubusercontent.com/assets/12499500/7812889/7f9a55ea-03b6-11e5-982d-72e087794980.png)
Malamut:
![bornyakorvmalamut1](https://cloud.githubusercontent.com/assets/12499500/7812894/885f345c-03b6-11e5-9cfa-f4dc38e2af5e.png)
![bornyakorvmalamut2](https://cloud.githubusercontent.com/assets/12499500/7812897/8d081fb4-03b6-11e5-830b-18c2cfd114f8.png)
Német Juhász:
![bornyakorvnemetjuhasz1](https://cloud.githubusercontent.com/assets/12499500/7812900/965f3098-03b6-11e5-908f-ce8ed84e82d2.png)
![bornyakorvnemetjuhasz2](https://cloud.githubusercontent.com/assets/12499500/7812903/9b8d79b2-03b6-11e5-9a8a-51008f7b170f.png)
Shar-Pei:
![bornyakorvsharpei1](https://cloud.githubusercontent.com/assets/12499500/7812913/a5dc3a3e-03b6-11e5-80fd-60a0af766300.png)
![bornyakorvsharpei2](https://cloud.githubusercontent.com/assets/12499500/7812916/ab74d410-03b6-11e5-9cd8-ca4322a4aaae.png)
Tacskó:
![bornyakorvtacsko1](https://cloud.githubusercontent.com/assets/12499500/7812920/b773daf4-03b6-11e5-96bc-c858ab13f22f.png)
![bornyakorvtacsko2](https://cloud.githubusercontent.com/assets/12499500/7812921/bb72a3ce-03b6-11e5-9b14-ec80517e1e0f.png)
Westie:
![bornyakorvwestie1](https://cloud.githubusercontent.com/assets/12499500/7812924/c0bf8734-03b6-11e5-8f1e-119e5908dec2.png)
![bornyakorvwestie2](https://cloud.githubusercontent.com/assets/12499500/7812926/c3d75032-03b6-11e5-9412-7bc997a7fe76.png)

Bocsi, hogy egyszerre küldöm, de hétvégén nem voltam net közelben >.<

**Comment by djozike** [comment]
a fekete bör Bulterrier nyakorv jobb szelen van egy kis fekete resz, azt ki tudnad javitani?

**Comment by Yuyumiko** [comment]
Bulterrierr javítva
![bornyakorvbullterrier2](https://cloud.githubusercontent.com/assets/12499500/7819412/e52daa08-03e1-11e5-816c-3f54c8056c04.png)

**Comment by Yuyumiko** [comment]
Husky:
![bornyakorvhusky1](https://cloud.githubusercontent.com/assets/12499500/7821407/ccb11926-03ee-11e5-8786-e939e5397acf.png)
![bornyakorvhusky2](https://cloud.githubusercontent.com/assets/12499500/7821409/d0a8707e-03ee-11e5-9a96-ae5fc58d5c60.png)

**Comment by djozike** [comment]
dalmata kepek mintha el lennének csuszva

**Comment by Yuyumiko** [comment]
Akita inu:
![bornyakorvakita1](https://cloud.githubusercontent.com/assets/12499500/7911992/c842d130-0863-11e5-9dd5-94dd1194a6ac.png)
![bornyakorvakita2](https://cloud.githubusercontent.com/assets/12499500/7911994/cb100446-0863-11e5-9543-d18f419583a7.png)

Amerikai Bulldog:
![bornyakorvamerikaibuldog1](https://cloud.githubusercontent.com/assets/12499500/7911982/bcfb59b4-0863-11e5-97cd-0ae49aa2a3f0.png)
![bornyakorvamerikaibuldog2](https://cloud.githubusercontent.com/assets/12499500/7911986/c124ea46-0863-11e5-86f9-323087903de1.png)

Dalmata(javított):
![bornyakorvdalmata1](https://cloud.githubusercontent.com/assets/12499500/7911999/d8b8c312-0863-11e5-8cf3-1b37e811db53.png)
![bornyakorvdalmata2](https://cloud.githubusercontent.com/assets/12499500/7912000/dbb381ba-0863-11e5-9e0d-1a0350004186.png)

Pitbull:
![bornyakorvpitbull1](https://cloud.githubusercontent.com/assets/12499500/7912002/e28a95d2-0863-11e5-931a-517a3535381c.png)
![bornyakorvpitbull2](https://cloud.githubusercontent.com/assets/12499500/7912004/e5e56964-0863-11e5-81e7-afefcfc65dea.png)

Whippet:
![bornyakorvwhippet1](https://cloud.githubusercontent.com/assets/12499500/7912008/ec0ae5f8-0863-11e5-8428-84ea47fe9e81.png)
![bornyakorvwhippet2](https://cloud.githubusercontent.com/assets/12499500/7912017/f5972424-0863-11e5-95ae-c9042d2d698e.png)

**Comment by Yuyumiko** [comment]
![bornyakorvbasenji2](https://cloud.githubusercontent.com/assets/12499500/7912644/b499bc6a-0869-11e5-8c44-3de09cd370f7.png)
Amerikai Stafforshire terrier:
![bornyakorvamstate1](https://cloud.githubusercontent.com/assets/12499500/7912640/a8083bb6-0869-11e5-8e9e-8f7805a91b98.png)
![bornyakorvamstate2](https://cloud.githubusercontent.com/assets/12499500/7912641/ab75edfc-0869-11e5-94ef-56dab5e969ba.png)

Basenji:
![bornyakorvbasenji1](https://cloud.githubusercontent.com/assets/12499500/7912643/b155f1fe-0869-11e5-89b9-2d0ed9e8ca87.png)

Belga Juhász:
![bornyakorvbelgajuhaszkutya1](https://cloud.githubusercontent.com/assets/12499500/7912647/b9aa2ed8-0869-11e5-9378-449c5c1e690a.png)
![bornyakorvbelgajuhaszkutya2](https://cloud.githubusercontent.com/assets/12499500/7912651/c2e3c19e-0869-11e5-8042-27ff0361f032.png)

Bernáthegyi:
![bornyakorvbernathegyi1](https://cloud.githubusercontent.com/assets/12499500/7912655/cb30c1bc-0869-11e5-8a2c-c2934b8ace0e.png)
![bornyakorvbernathegyi2](https://cloud.githubusercontent.com/assets/12499500/7912657/d1aae824-0869-11e5-8fe9-7bc3eaa5a9bc.png)

Boxer:
![bornyakorvboxer1](https://cloud.githubusercontent.com/assets/12499500/7912662/d9744f64-0869-11e5-883e-35e48bd3e5c5.png)
![bornyakorvboxer2](https://cloud.githubusercontent.com/assets/12499500/7912663/ddb3b4e8-0869-11e5-97d4-46c5652c059d.png)

Cardigan Welsh Corgi:
![bornyakorvcardigan1](https://cloud.githubusercontent.com/assets/12499500/7912667/e9e8634e-0869-11e5-8b88-afd13892b5a3.png)
![bornyakorvcardigan2](https://cloud.githubusercontent.com/assets/12499500/7912669/f03640ae-0869-11e5-85cb-41eeba390de8.png)

Csehszlovák Farkas:
![bornyakorvcsehszlovakfarkas1](https://cloud.githubusercontent.com/assets/12499500/7912673/fb15a988-0869-11e5-8a23-4c873b9423f9.png)
![bornyakorvcsehszlovakfarkas2](https://cloud.githubusercontent.com/assets/12499500/7912675/00e04788-086a-11e5-9375-fda890f4bcca.png)

Dobermann:
![bornyakorvdobermann1](https://cloud.githubusercontent.com/assets/12499500/7912683/0b12866c-086a-11e5-9aa2-9cb52ff41dfb.png)
![bornyakorvdobermann2](https://cloud.githubusercontent.com/assets/12499500/7912689/1211bc8a-086a-11e5-8c4b-3202c9fbc09a.png)

Golden Retriver:
![bornyakorvgoldenretriver1](https://cloud.githubusercontent.com/assets/12499500/7912699/1ec50590-086a-11e5-8d6d-f864d3a46aa8.png)
![bornyakorvgoldenretriver2](https://cloud.githubusercontent.com/assets/12499500/7912705/24654b72-086a-11e5-809f-50b0eec23030.png)

**Comment by Yuyumiko** [comment]
Amerikai Stafforshire terrier(Javított):
![bornyakorvamstate1](https://cloud.githubusercontent.com/assets/12499500/7913456/680276b0-0870-11e5-849e-d6d529de6ee4.png)
![bornyakorvamstate2](https://cloud.githubusercontent.com/assets/12499500/7913457/6a457044-0870-11e5-8c09-2929f1459fc9.png)

**Comment by Yuyumiko** [comment]
Izlandi Juhász:
![bornyakorvizlandi1](https://cloud.githubusercontent.com/assets/12499500/7913947/fbe34a0a-0873-11e5-8108-c8e0e1f4c536.png)
![bornyakorvizlandi2](https://cloud.githubusercontent.com/assets/12499500/7913950/feaf45c2-0873-11e5-81ea-9de2e31066d5.png)

Kínai Mesztelen kutya:
![bornyakorvkinaimesztelenkutya1](https://cloud.githubusercontent.com/assets/12499500/7913955/0848b316-0874-11e5-803b-b2a352ebaef7.png)
![bornyakorvkinaimesztelenkutya2](https://cloud.githubusercontent.com/assets/12499500/7913958/0c1ca92a-0874-11e5-8502-02290270acbf.png)

Kishu Inu:
![bornyakorvkishuinu1](https://cloud.githubusercontent.com/assets/12499500/7913964/119082c8-0874-11e5-81e2-2e9f00e39b16.png)
![bornyakorvkishuinu2](https://cloud.githubusercontent.com/assets/12499500/7913966/14521d1e-0874-11e5-91a6-42b6fe0e153f.png)

Mopsz:
![bornyakorvmops1](https://cloud.githubusercontent.com/assets/12499500/7913973/197cce6a-0874-11e5-8670-f37efb3d0f2e.png)
![bornyakorvmops2](https://cloud.githubusercontent.com/assets/12499500/7913977/1c39414c-0874-11e5-8aaa-36898037d7b1.png)

**Comment by Yuyumiko** [comment]
Saarloosi:
![bornyakorvsaarloosi1](https://cloud.githubusercontent.com/assets/12499500/7918443/b774937e-0891-11e5-8fec-d68e37502b55.png)
![bornyakorvsaarloosi2](https://cloud.githubusercontent.com/assets/12499500/7918449/c4426c7a-0891-11e5-9fde-13c2411a0885.png)

**Comment by djozike** [comment]
Hu mennyit dolgoztál, nem semmi, viszont a bernáthegyi hátterében maradtak foltok

**Comment by Yuyumiko** [comment]
A gépem vírusos lett, ezért szervizbe kellett küldeni, péntekre készlesz. Tehét a következő nyakörveknek csak pénteken tudok neki esni.
Viszont a maltese-re nem tudom úgy rárakni, hogy normálisan nézzen ki... Javasolhatám esetleg a lecserélését?

**Comment by Yuyumiko** [comment]
Német juhásznál elcsúszott a nyakorv pénteken azt is korrigálom

**Comment by Yuyumiko** [comment]
Itt van 2 javított:
Német juhász:
![bornyakorvnemetjuhaszkutya1](https://cloud.githubusercontent.com/assets/12499500/8036357/96de31c2-0df7-11e5-9865-f3ef6907bcc8.png)
![bornyakorvnemetjuhaszkutya2](https://cloud.githubusercontent.com/assets/12499500/8036364/9e0d6206-0df7-11e5-9d5d-9d9c0b6f5613.png)

Bernáthegyi:
![bornyakorvbernathegyi1](https://cloud.githubusercontent.com/assets/12499500/8036371/ab203b26-0df7-11e5-970c-b7fcd264db49.png)
![bornyakorvbernathegyi2](https://cloud.githubusercontent.com/assets/12499500/8036375/b18175e8-0df7-11e5-9f01-ff09e4621650.png)
